### ISSUE TITLE
No equilibration is done in water box simulations

### ISSUE THREAD

**Issue by adambaskerville** [Exscientia/StableNetGuardOwl#28]
Did we not want to equilibrate ther water structure before the simulation? In `protocols.py` there is a placeholder (`nr_of_equilibrium_steps` (typo ?)) but this is never actually done from what I can see, the same for the `run_organic_liquid_test`.

**Comment by wiederm** [comment]
That is true. The water box is initialized from a equilibrated water box, that is the reason this has been removed.
